package PhoneApp;


/**
* PhoneApp/PhoneOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Phone.idl
* 26 марта 2017 г. 17:13:18 MSK
*/

public interface PhoneOperations 
{
  String viewInfo ();
  boolean addInfo ();
  boolean editInfo ();
  boolean deleteInfo ();
  void shutdown ();
} // interface PhoneOperations
