package PhoneApp;


/**
* PhoneApp/PhoneOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Phone.idl
* 27 марта 2017 г. 16:30:37 MSK
*/

public interface PhoneOperations 
{
  String viewInfo ();
  boolean addInfo (String note);
  boolean editInfo (int number, String note);
  boolean deleteInfo (int number);
  void shutdown ();
} // interface PhoneOperations
