package PhoneApp;


/**
* PhoneApp/Phone.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Phone.idl
* 27 марта 2017 г. 16:30:37 MSK
*/

public interface Phone extends PhoneOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Phone
