package PhoneApp;


/**
* PhoneApp/PhonePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Phone.idl
* 27 марта 2017 г. 16:30:37 MSK
*/

public abstract class PhonePOA extends org.omg.PortableServer.Servant
 implements PhoneApp.PhoneOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("viewInfo", new java.lang.Integer (0));
    _methods.put ("addInfo", new java.lang.Integer (1));
    _methods.put ("editInfo", new java.lang.Integer (2));
    _methods.put ("deleteInfo", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // PhoneApp/Phone/viewInfo
       {
         String $result = null;
         $result = this.viewInfo ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // PhoneApp/Phone/addInfo
       {
         String note = in.read_string ();
         boolean $result = false;
         $result = this.addInfo (note);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // PhoneApp/Phone/editInfo
       {
         int number = in.read_long ();
         String note = in.read_string ();
         boolean $result = false;
         $result = this.editInfo (number, note);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // PhoneApp/Phone/deleteInfo
       {
         int number = in.read_long ();
         boolean $result = false;
         $result = this.deleteInfo (number);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // PhoneApp/Phone/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PhoneApp/Phone:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Phone _this() 
  {
    return PhoneHelper.narrow(
    super._this_object());
  }

  public Phone _this(org.omg.CORBA.ORB orb) 
  {
    return PhoneHelper.narrow(
    super._this_object(orb));
  }


} // class PhonePOA
