package PhoneApp;


/**
* PhoneApp/PhoneHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Phone.idl
* 27 марта 2017 г. 16:30:37 MSK
*/

abstract public class PhoneHelper
{
  private static String  _id = "IDL:PhoneApp/Phone:1.0";

  public static void insert (org.omg.CORBA.Any a, PhoneApp.Phone that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PhoneApp.Phone extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (PhoneApp.PhoneHelper.id (), "Phone");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PhoneApp.Phone read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PhoneStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PhoneApp.Phone value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static PhoneApp.Phone narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PhoneApp.Phone)
      return (PhoneApp.Phone)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PhoneApp._PhoneStub stub = new PhoneApp._PhoneStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static PhoneApp.Phone unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PhoneApp.Phone)
      return (PhoneApp.Phone)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PhoneApp._PhoneStub stub = new PhoneApp._PhoneStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
