module PhoneApp {
  interface Phone{
          string viewInfo();
          boolean addInfo(in string note);
          boolean editInfo(in long number, in string note);
          boolean deleteInfo(in long number);
  oneway void shutdown();
};
};